---
language: python
python: "2.7"
cache: pip
# Use the new container infrastructure
sudo: required
services:
  - docker

# Install ansible
addons:
  apt:
    packages:
      - python-pip
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  - pip install molecule docker
  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - molecule test -s docker
  - molecule test -s cluster


notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
