---
- name: Converge
  hosts: all
  vars:
    enable_cluster: true
    use_longname: false
    cluster_nodes: "'rabbitmq@node1','rabbitmq@node2','rabbitmq@node3'"
  roles:
    - role: ansible-role-rabbitmq
